import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, AlertTriangle, ArrowRight, Building2, Check, Clock3, Download, FileText, Landmark, Mail, MapPin, Phone, Printer, Save, Send, ShieldCheck, UserRound, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { ActionDialog, DataTable, Field, MetricStrip, MiniStats, PageHeader, Panel, SelectField, TabsBar, submitWithToast, type Column, type TableRowData } from "./ui";

const money = (n: number) => `৳${n.toLocaleString("en-US")}`;
const chartData = [
  { month: "Jan", sales: 28, purchase: 20 }, { month: "Feb", sales: 34, purchase: 26 }, { month: "Mar", sales: 31, purchase: 22 },
  { month: "Apr", sales: 42, purchase: 29 }, { month: "May", sales: 46, purchase: 33 }, { month: "Jun", sales: 51, purchase: 39 },
  { month: "Jul", sales: 48, purchase: 34 }, { month: "Aug", sales: 58, purchase: 42 }, { month: "Sep", sales: 62, purchase: 44 },
];
const baseColumns: Column[] = [{ key: "ref", label: "Reference" }, { key: "party", label: "Party" }, { key: "date", label: "Date" }, { key: "status", label: "Status", status: true }, { key: "amount", label: "Amount", align: "right" }];
const salesRows = [
  { ref: "SO-2609-041", party: "Aurora Apparels Ltd.", date: "12 Sep 2026", status: "Approved", amount: money(284500) },
  { ref: "SO-2609-040", party: "Northern Knitwear", date: "12 Sep 2026", status: "Pending", amount: money(168200) },
  { ref: "SO-2609-039", party: "Bengal Stitch Works", date: "11 Sep 2026", status: "Partial", amount: money(92500) },
  { ref: "SO-2609-038", party: "Metro Fashions", date: "11 Sep 2026", status: "Completed", amount: money(412800) },
  { ref: "SO-2609-037", party: "Eastern Denim Co.", date: "10 Sep 2026", status: "Overdue", amount: money(137600) },
  { ref: "SO-2609-036", party: "Riviera Garments", date: "10 Sep 2026", status: "Approved", amount: money(221400) },
];
const inventoryRows = [
  { sku: "BTN-SHL-18-WHT", product: "Shell Button 18L · White", category: "Buttons", warehouse: "Tejgaon", available: "48,200 pcs", reserved: "12,000", status: "In Stock" },
  { sku: "ZIP-NYL-09-BLK", product: "Nylon Zipper 9in · Black", category: "Zippers", warehouse: "Tejgaon", available: "3,450 pcs", reserved: "1,800", status: "Low Stock" },
  { sku: "LBL-WVN-40", product: "Woven Main Label 40mm", category: "Labels", warehouse: "Gazipur", available: "72,000 pcs", reserved: "32,500", status: "In Stock" },
  { sku: "ELA-WOV-25", product: "Woven Elastic 25mm", category: "Elastic", warehouse: "Gazipur", available: "980 m", reserved: "700", status: "Low Stock" },
  { sku: "TAP-TWL-15", product: "Cotton Twill Tape 15mm", category: "Tapes", warehouse: "Narayanganj", available: "0 m", reserved: "0", status: "Out of Stock" },
];

const entityFields = [
  { label: "Name", name: "name", required: true },
  { label: "Contact person", name: "contact", required: true },
  { label: "Phone", name: "phone", required: true },
  { label: "Email", name: "email", type: "email", required: true },
  { label: "Payment terms", name: "terms", options: ["Cash", "15 days", "30 days", "45 days"] },
  { label: "Credit limit", name: "limit", type: "number" },
];

function useActionDialog() {
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Record<string, string> | undefined>();
  return { open, setOpen, editing, create: () => { setEditing(undefined); setOpen(true); }, edit: (row: TableRowData) => { setEditing(Object.fromEntries(Object.entries(row).map(([key, value]) => [key, String(value)]))); setOpen(true); } };
}

export function DashboardScreen() {
  const [period, setPeriod] = useState("Month");
  const dialog = useActionDialog();
  const factor = period === "Day" ? 0.04 : period === "Year" ? 9.7 : 1;
  return <><PageHeader eyebrow="Overview / September 2026" title="Trading dashboard" description="Commercial, inventory and cash position across all operating units." action="Record transaction" onAction={dialog.create} />
    <div className="mb-4 flex w-fit rounded-lg border bg-card p-1 shadow-card">{["Day", "Month", "Year"].map((p) => <button type="button" key={p} onClick={() => setPeriod(p)} className={`h-7 rounded-md px-3 text-[11px] font-semibold transition-colors ${period === p ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-muted"}`}>{p}</button>)}</div>
    <MetricStrip items={[{ label: `Sales · ${period}`, value: money(Math.round(6248000*factor)), detail: "12.4% vs previous period", tone: "up" }, { label: `Purchase · ${period}`, value: money(Math.round(4126000*factor)), detail: "8.1% vs previous period", tone: "up" }, { label: "Trade receivable", value: money(2845000), detail: "৳418K overdue", tone: "down" }, { label: "Trade payable", value: money(1968000), detail: "৳620K due this week", tone: "neutral" }]} />
    <div className="mb-4 grid border-l border-t bg-card sm:grid-cols-3"><div className="border-b border-r p-3"><div className="text-[10px] uppercase text-muted-foreground">Cash & bank</div><div className="mt-1 text-base font-semibold">{money(3875000)}</div></div><div className="border-b border-r p-3"><div className="text-[10px] uppercase text-muted-foreground">Stock value</div><div className="mt-1 text-base font-semibold">{money(8124000)}</div></div><div className="border-b border-r p-3"><div className="text-[10px] uppercase text-muted-foreground">Gross margin</div><div className="mt-1 text-base font-semibold">33.96%</div></div></div>
    <div className="grid gap-5 xl:grid-cols-[1.65fr_1fr]"><Panel title="Monthly sales vs purchase" subtitle="Amounts in lakh BDT" action={<div className="flex gap-4 text-[10px] font-medium"><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-primary"/>Sales</span><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-chart-2"/>Purchase</span></div>}><div className="h-64 p-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity={0.25}/><stop offset="1" stopColor="var(--primary)" stopOpacity={0.01}/></linearGradient><linearGradient id="purchaseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--chart-2)" stopOpacity={0.18}/><stop offset="1" stopColor="var(--chart-2)" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeDasharray="4 5" vertical={false}/><XAxis dataKey="month" tick={{ fontSize: 10 }} axisLine={false}/><YAxis tick={{ fontSize: 10 }} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="sales" stroke="var(--primary)" fill="url(#salesFill)" strokeWidth={2.5}/><Area type="monotone" dataKey="purchase" stroke="var(--chart-2)" fill="url(#purchaseFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel>
    <Panel title="Low stock alerts" subtitle="5 products below minimum"><div className="divide-y">{inventoryRows.slice(1).map((r) => <div key={r.sku} className="flex items-center gap-3 px-3 py-2.5"><AlertTriangle className="size-4 shrink-0 text-warning"/><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium">{r.product}</div><div className="text-[10px] text-muted-foreground">{r.sku} · {r.warehouse}</div></div><div className="text-right text-[11px] font-semibold tabular-nums">{r.available}</div></div>)}</div></Panel></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Top buyers" subtitle="By net sales this month"><DataTable searchable={false} columns={[{key:"name",label:"Buyer"},{key:"orders",label:"Orders",align:"right"},{key:"sales",label:"Net sales",align:"right"}]} rows={[{name:"Aurora Apparels Ltd.",orders:18,sales:money(1480000)},{name:"Metro Fashions",orders:14,sales:money(1195000)},{name:"Northern Knitwear",orders:11,sales:money(934000)}]}/></Panel><Panel title="Top-selling products" subtitle="By issued quantity"><DataTable searchable={false} columns={[{key:"sku",label:"SKU"},{key:"product",label:"Product"},{key:"qty",label:"Quantity",align:"right"}]} rows={inventoryRows.slice(0,3).map((r,i)=>({sku:r.sku,product:r.product,qty:[96500,72000,68400][i] ?? 0}))}/></Panel></div><ActionDialog open={dialog.open} onOpenChange={dialog.setOpen} title="Record transaction" description="Add a cash, bank, purchase, or sales transaction." fields={[{label:"Transaction type",name:"type",options:["Cash receipt","Bank payment","Sales receipt","Purchase payment"],required:true},{label:"Party",name:"party",required:true},{label:"Amount",name:"amount",type:"number",required:true},{label:"Date",name:"date",type:"date",required:true},{label:"Reference",name:"reference"},{label:"Notes",name:"notes"}]}/></>;
}

const partyConfig = {
  buyer: { title: "Buyer management", entity: "Buyer", description: "Credit control, sales history and account statements for garment manufacturers.", tabs: ["Buyer list", "Profile", "Sales history", "Outstanding", "Ledger", "Statement"] },
  supplier: { title: "Supplier management", entity: "Supplier", description: "Purchase relationships, payable positions and payment histories.", tabs: ["Supplier list", "Profile", "Purchase history", "Payable", "Ledger", "Payments"] },
};
export function PartyScreen({ kind }: { kind: "buyer" | "supplier" }) {
  const config = partyConfig[kind]; const [tab, setTab] = useState(config.tabs[0] ?? "Profile");
  const rows = kind === "buyer" ? [
    { code:"BUY-001", name:"Aurora Apparels Ltd.", contact:"Samira Hossain", terms:"30 days", limit:money(2500000), balance:money(482000), status:"Active" },
    { code:"BUY-002", name:"Northern Knitwear", contact:"Fahim Chowdhury", terms:"45 days", limit:money(1800000), balance:money(630000), status:"Review" },
    { code:"BUY-003", name:"Metro Fashions", contact:"Tasnim Alam", terms:"30 days", limit:money(3000000), balance:money(294500), status:"Active" },
  ] : [
    { code:"SUP-011", name:"YKK Bangladesh", contact:"Rashed Karim", terms:"30 days", limit:money(0), balance:money(740000), status:"Active" },
    { code:"SUP-018", name:"Delta Button Industries", contact:"Imran Haque", terms:"Cash", limit:money(0), balance:money(125000), status:"Active" },
    { code:"SUP-024", name:"Prime Label Works", contact:"Nusrat Jahan", terms:"45 days", limit:money(0), balance:money(485000), status:"Review" },
  ];
  return <><PageHeader eyebrow={`Partners / ${kind === "buyer" ? "Receivables" : "Payables"}`} title={config.title} description={config.description} action={`Add ${config.entity.toLowerCase()}`} /><Panel title={`${config.entity} workspace`} subtitle="Select a view to inspect account activity"><TabsBar tabs={config.tabs} active={tab} onChange={setTab}/>{tab.includes("list") ? <DataTable columns={[{key:"code",label:"Code"},{key:"name",label:config.entity},{key:"contact",label:"Contact"},{key:"terms",label:"Payment terms"},{key:"limit",label:"Credit limit",align:"right"},{key:"balance",label:kind === "buyer"?"Outstanding":"Payable",align:"right"},{key:"status",label:"Status",status:true}]} rows={rows}/> : tab === "Profile" ? <PartyProfile kind={kind}/> : <DataTable columns={baseColumns} rows={salesRows.map((r,i)=>({...r,party:rows[i%rows.length]?.name ?? "Unknown",ref:`${kind === "buyer"?"INV":"PI"}-2609-${String(91-i).padStart(3,"0")}`}))}/>}</Panel></>;
}
function PartyProfile({kind}:{kind:"buyer"|"supplier"}) { return <div className="grid lg:grid-cols-[300px_1fr]"><div className="border-r p-4"><div className="mb-4 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-sm bg-primary text-xs font-bold text-primary-foreground">AA</div><div><div className="text-sm font-semibold">{kind==="buyer"?"Aurora Apparels Ltd.":"YKK Bangladesh"}</div><div className="text-[10px] text-muted-foreground">Active since 2021</div></div></div><dl className="grid grid-cols-2 gap-y-3 text-[11px]"><dt className="text-muted-foreground">Contact</dt><dd>Samira Hossain</dd><dt className="text-muted-foreground">Phone</dt><dd>+880 1712 334455</dd><dt className="text-muted-foreground">Terms</dt><dd>30 days</dd><dt className="text-muted-foreground">Credit limit</dt><dd>{money(2500000)}</dd></dl></div><div className="p-4"><MetricStrip items={[{label:kind==="buyer"?"Net sales":"Net purchases",value:money(4280000),detail:"This financial year",tone:"up"},{label:kind==="buyer"?"Outstanding":"Payable",value:money(482000),detail:"3 open invoices"},{label:"Last payment",value:money(280000),detail:"08 Sep 2026"},{label:"Available credit",value:money(2018000),detail:"80.7% available",tone:"up"}]}/><DataTable columns={baseColumns} rows={salesRows.slice(0,4)}/></div></div> }

export function ProductsScreen() { const [tab,setTab]=useState("Product list"); return <><PageHeader eyebrow="Inventory setup" title="Product & accessories master" description="Maintain SKU, commercial pricing and minimum stocking rules." action="Add product"/><Panel title="Product master"><TabsBar tabs={["Product list","Add / edit product","Categories & units"]} active={tab} onChange={setTab}/>{tab==="Product list"?<DataTable columns={[{key:"sku",label:"SKU"},{key:"product",label:"Product"},{key:"category",label:"Category"},{key:"color",label:"Color"},{key:"size",label:"Size"},{key:"unit",label:"Unit"},{key:"purchase",label:"Purchase",align:"right"},{key:"sales",label:"Sales",align:"right"},{key:"status",label:"Status",status:true}]} rows={inventoryRows.map((r,i)=>({...r,color:["White","Black","Navy","Natural","Ecru"][i] ?? "—",size:["18L","9 inch","40mm","25mm","15mm"][i] ?? "—",unit:i===3||i===4?"Meter":"Piece",purchase:money([2.1,18,1.8,12,8][i] ?? 0),sales:money([2.8,24,2.5,16,11][i] ?? 0)}))}/>:<FormGrid title="Product information" fields={["SKU","Product name","Category","Unit","Color","Size","Minimum stock","Purchase price","Sales price"]}/>}</Panel></> }

function FormGrid({title,fields}:{title:string;fields:string[]}) { return <div className="p-4"><h3 className="mb-3 text-xs font-semibold">{title}</h3><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{fields.map((f,i)=><Field key={f} label={f} {...(i === 0 ? { defaultValue: "BTN-SHL-18-WHT" } : {})} placeholder={`Enter ${f.toLowerCase()}`}/>)}</div><div className="mt-4 flex justify-end gap-2"><Button variant="outline" size="sm" className="rounded-sm shadow-none">Cancel</Button><Button size="sm" className="rounded-sm shadow-none"><Save/>Save record</Button></div></div> }

export function PurchaseScreen() { const [tab,setTab]=useState("Purchase orders"); return <><PageHeader eyebrow="Procurement" title="Purchase" description="Create purchase orders, receive supplier invoices and control pending commitments." action="New purchase order"/><MetricStrip items={[{label:"Open PO value",value:money(1840000),detail:"7 purchase orders"},{label:"Awaiting approval",value:money(620000),detail:"3 orders",tone:"down"},{label:"Due to suppliers",value:money(1968000),detail:"Next 30 days"},{label:"Received this month",value:money(4126000),detail:"↑ 8.1%",tone:"up"}]}/><Panel title="Purchase workspace"><TabsBar tabs={["Purchase orders","PO detail","Purchase invoice","Supplier payment","Pending PO"]} active={tab} onChange={setTab}/>{tab==="PO detail"?<OrderDetail purchase/>:tab==="Purchase invoice"||tab==="Supplier payment"?<TransactionForm type={tab}/>:<DataTable columns={baseColumns} rows={salesRows.map((r,i)=>({...r,ref:`PO-2609-${String(66-i).padStart(3,"0")}`,party:["YKK Bangladesh","Delta Button Industries","Prime Label Works"][i%3] ?? "Unknown"}))}/>}</Panel></> }

export function SalesScreen() { const [tab,setTab]=useState("Sales orders"); return <><PageHeader eyebrow="Commercial" title="Sales" description="Manage customer orders, deliveries, invoices, returns and collections." action="New sales order"/><MetricStrip items={[{label:"Sales this month",value:money(6248000),detail:"↑ 12.4%",tone:"up"},{label:"Pending delivery",value:money(930000),detail:"8 orders"},{label:"Receivable",value:money(2845000),detail:"14 invoices"},{label:"Returns",value:money(86000),detail:"1.37% of sales"}]}/><Panel title="Sales workspace"><TabsBar tabs={["Sales orders","Order form","Delivery chalan","Sales invoice","Sales return","Collection","Sales history"]} active={tab} onChange={setTab}/>{["Order form","Delivery chalan","Sales invoice","Sales return","Collection"].includes(tab)?<TransactionForm type={tab}/>:<DataTable columns={baseColumns} rows={salesRows}/>}</Panel></> }

function OrderDetail({purchase=false}:{purchase?:boolean}) { return <div className="grid gap-0 lg:grid-cols-[280px_1fr]"><div className="border-r p-4"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-semibold">{purchase?"PO-2609-066":"SO-2609-041"}</span><span className="border border-warning/30 bg-warning-soft px-2 py-1 text-[10px] font-medium text-warning">Awaiting approval</span></div><dl className="grid grid-cols-2 gap-y-3 text-[11px]"><dt className="text-muted-foreground">Party</dt><dd>{purchase?"YKK Bangladesh":"Aurora Apparels"}</dd><dt className="text-muted-foreground">Order date</dt><dd>12 Sep 2026</dd><dt className="text-muted-foreground">Due date</dt><dd>28 Sep 2026</dd><dt className="text-muted-foreground">Warehouse</dt><dd>Tejgaon</dd><dt className="text-muted-foreground">Created by</dt><dd>Nadia Rahman</dd></dl><p className="mt-6 border-t pt-3 text-[10px] leading-5 text-muted-foreground">Commercial terms verified. Delivery schedule is split across two consignments.</p></div><div><div className="flex justify-end gap-2 border-b p-3"><Button variant="outline" size="sm" className="rounded-sm shadow-none"><X/>Decline</Button><Button size="sm" className="rounded-sm shadow-none"><Check/>Approve</Button></div><DataTable searchable={false} columns={[{key:"item",label:"Item"},{key:"sku",label:"SKU"},{key:"qty",label:"Quantity",align:"right"},{key:"rate",label:"Rate",align:"right"},{key:"total",label:"Total",align:"right"}]} rows={inventoryRows.slice(0,4).map((r,i)=>({item:r.product,sku:r.sku,qty:[10000,4200,15000,5000][i] ?? 0,rate:money([2.1,18,1.8,12][i] ?? 0),total:money([21000,75600,27000,60000][i] ?? 0)}))}/></div></div> }
function TransactionForm({type}:{type:string}) { return <div className="p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><SelectField label={type.includes("Payment")?"Supplier":"Buyer / supplier"} options={["Aurora Apparels Ltd.","YKK Bangladesh","Metro Fashions"]}/><Field label="Reference" defaultValue="AUTO"/><Field label="Transaction date" type="date" defaultValue="2026-09-12"/><SelectField label="Warehouse / Account" options={["Tejgaon Warehouse","City Bank - Current","Cash in hand"]}/></div><div className="mt-4 border"><DataTable searchable={false} columns={[{key:"item",label:"Item / Description"},{key:"qty",label:"Quantity",align:"right"},{key:"rate",label:"Rate",align:"right"},{key:"tax",label:"VAT",align:"right"},{key:"total",label:"Total",align:"right"}]} rows={[{item:"Nylon Zipper 9in · Black",qty:"4,200 pcs",rate:money(18),tax:"5%",total:money(79380)},{item:"Woven Main Label 40mm",qty:"15,000 pcs",rate:money(1.8),tax:"5%",total:money(28350)}]}/></div><div className="mt-4 flex justify-end gap-2"><Button variant="outline" size="sm" className="rounded-sm shadow-none">Save draft</Button><Button size="sm" className="rounded-sm shadow-none"><Save/>Save & submit</Button></div></div> }

export function InventoryScreen() { const [tab,setTab]=useState("Stock overview"); return <><PageHeader eyebrow="Inventory control" title="Inventory" description="Live stock position, movement traceability and replenishment alerts." action="Stock adjustment"/><MetricStrip items={[{label:"Stock value",value:money(8124000),detail:"Across 3 warehouses"},{label:"Available SKUs",value:"1,248",detail:"96 active categories"},{label:"Low stock",value:"5",detail:"Requires action",tone:"down"},{label:"Today's movements",value:"38",detail:"22 in · 16 out"}]}/><Panel title="Product stock detail" subtitle="Warehouse and transaction-level visibility"><TabsBar tabs={["Stock overview","Stock in / out","Manual adjustment","Low-stock alert","Movement history"]} active={tab} onChange={setTab}/>{tab==="Manual adjustment"?<FormGrid title="Manual stock adjustment" fields={["Product / SKU","Warehouse","Adjustment type","Quantity","Unit cost","Reference","Reason"]}/>:<DataTable columns={[{key:"sku",label:"SKU"},{key:"product",label:"Product"},{key:"category",label:"Category"},{key:"warehouse",label:"Warehouse"},{key:"available",label:"Available",align:"right"},{key:"reserved",label:"Reserved",align:"right"},{key:"status",label:"Status",status:true}]} rows={inventoryRows}/>}</Panel></> }

export function DocumentsScreen(){ const [kind,setKind]=useState("Tax Invoice"); return <><PageHeader eyebrow="Documents" title="Invoice & chalan generator" description="Compose commercial documents and verify the exact print layout before issue." action="New document"/><div className="grid min-h-[670px] border bg-card lg:grid-cols-2"><div className="border-r"><div className="flex items-center justify-between border-b px-4 py-3"><div className="flex gap-1">{["Tax Invoice","Delivery Chalan"].map(k=><button type="button" key={k} onClick={()=>setKind(k)} className={`h-8 px-3 text-xs ${kind===k?"bg-primary text-primary-foreground":"border"}`}>{k}</button>)}</div><Button variant="outline" size="sm" className="rounded-sm shadow-none">Save draft</Button></div><div className="p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Document number" defaultValue={kind==="Tax Invoice"?"INV-2609-041":"DC-2609-028"}/><Field label="Issue date" type="date" defaultValue="2026-09-12"/><SelectField label="Buyer" options={["Aurora Apparels Ltd.","Metro Fashions"]}/><Field label="Sales order" defaultValue="SO-2609-041"/></div><div className="mt-5"><DataTable searchable={false} columns={[{key:"item",label:"Item"},{key:"qty",label:"Qty",align:"right"},{key:"rate",label:"Rate",align:"right"},{key:"total",label:"Total",align:"right"}]} rows={[{item:"Shell Button 18L",qty:"10,000",rate:"৳2.80",total:money(28000)},{item:"Nylon Zipper 9in",qty:"4,200",rate:"৳24.00",total:money(100800)}]}/></div><label className="mt-4 grid gap-1 text-[11px] font-medium">Notes<Textarea defaultValue="Goods supplied against approved sales order. Please acknowledge receipt." className="rounded-sm text-xs shadow-none"/></label></div></div><DocumentPreview kind={kind}/></div></> }
function DocumentPreview({kind}:{kind:string}){return <div className="bg-workspace p-4 sm:p-8"><div className="mx-auto min-h-[600px] max-w-xl border bg-background p-6 shadow-print"><div className="flex justify-between border-b pb-5"><div><div className="text-lg font-extrabold tracking-wide text-primary">GARMENTTRADE</div><div className="mt-1 text-[9px] leading-4 text-muted-foreground">Accessories Trading Co.<br/>Tejgaon Industrial Area, Dhaka 1208</div></div><div className="text-right"><h2 className="text-xl font-semibold">{kind}</h2><p className="text-[10px] text-muted-foreground"># {kind==="Tax Invoice"?"INV-2609-041":"DC-2609-028"}</p></div></div><div className="grid grid-cols-2 py-5 text-[10px]"><div><div className="text-muted-foreground">Billed to</div><div className="mt-1 font-semibold">Aurora Apparels Ltd.</div><div>Gazipur, Dhaka</div></div><div className="text-right"><div><span className="text-muted-foreground">Issue date:</span> 12 Sep 2026</div><div><span className="text-muted-foreground">Order:</span> SO-2609-041</div></div></div><table className="w-full text-[10px]"><thead className="border-y bg-table-head"><tr><th className="py-2 text-left">Item</th><th className="text-right">Qty</th><th className="text-right">Rate</th><th className="text-right">Total</th></tr></thead><tbody><tr className="border-b"><td className="py-3">Shell Button 18L · White</td><td className="text-right">10,000</td><td className="text-right">৳2.80</td><td className="text-right">৳28,000</td></tr><tr className="border-b"><td className="py-3">Nylon Zipper 9in · Black</td><td className="text-right">4,200</td><td className="text-right">৳24.00</td><td className="text-right">৳100,800</td></tr></tbody></table><div className="ml-auto mt-4 w-48 text-[10px]"><div className="flex justify-between py-1"><span>Subtotal</span><span>৳128,800</span></div><div className="flex justify-between py-1"><span>VAT 5%</span><span>৳6,440</span></div><div className="flex justify-between border-t py-2 text-xs font-bold"><span>Total</span><span>৳135,240</span></div></div><div className="mt-32 grid grid-cols-2 gap-16 text-center text-[9px]"><div className="border-t pt-2">Authorized signature</div><div className="border-t pt-2">Receiver signature</div></div></div><div className="mt-3 flex justify-center gap-2"><Button variant="outline" size="sm" className="rounded-sm shadow-none"><Printer/>Print</Button><Button size="sm" className="rounded-sm shadow-none"><Send/>Issue document</Button></div></div>}

export function CashBankScreen(){return <><PageHeader eyebrow="Treasury" title="Cash & bank" description="Daily liquidity, manual entries and reconciled account statements." action="New transaction"/><MetricStrip items={[{label:"Cash in hand",value:money(485000),detail:"2 cash accounts"},{label:"Bank balance",value:money(3390000),detail:"4 bank accounts"},{label:"Today's receipts",value:money(428000),detail:"9 transactions",tone:"up"},{label:"Today's payments",value:money(316500),detail:"7 transactions"}]}/><div className="grid gap-4 xl:grid-cols-[1fr_2fr]"><Panel title="Account balances"><div className="divide-y">{[["City Bank · Current",2184000],["BRAC Bank · Current",1206000],["Head office cash",375000],["Petty cash",110000]].map(a=><div key={a[0]} className="flex justify-between px-3 py-3 text-xs"><span>{a[0]}</span><strong>{money(Number(a[1]))}</strong></div>)}</div></Panel><Panel title="Day-wise statement"><DataTable columns={[{key:"ref",label:"Reference"},{key:"details",label:"Particulars"},{key:"account",label:"Account"},{key:"receipt",label:"Receipt",align:"right"},{key:"payment",label:"Payment",align:"right"},{key:"balance",label:"Balance",align:"right"}]} rows={salesRows.map((r,i)=>({ref:`TXN-2609-${181-i}`,details:i%2?"Supplier payment":"Buyer collection",account:i%2?"City Bank":"BRAC Bank",receipt:i%2?"—":r.amount,payment:i%2?r.amount:"—",balance:money(3390000-i*124000)}))}/></Panel></div></>}

export function ApprovalsScreen(){ const [selected,setSelected]=useState(0); return <><PageHeader eyebrow="Controls" title="Approval workflow" description="Review purchase, sales, payment and stock requests awaiting authorization." action="Approval rules"/><div className="grid min-h-[590px] border bg-card lg:grid-cols-[380px_1fr]"><div className="border-r"><div className="border-b px-3 py-3 text-xs font-semibold">Pending queue <span className="ml-1 text-muted-foreground">(12)</span></div>{salesRows.slice(0,5).map((r,i)=><button type="button" key={r.ref} onClick={()=>setSelected(i)} className={`block w-full border-b px-3 py-3 text-left ${selected===i?"border-l-2 border-l-primary bg-accent":"hover:bg-muted"}`}><div className="flex justify-between text-xs font-medium"><span>{i%2?"Supplier payment":"Purchase order"}</span><span>{r.amount}</span></div><div className="mt-1 flex justify-between text-[10px] text-muted-foreground"><span>{r.party}</span><span>{r.date}</span></div></button>)}</div><div><div className="flex items-center justify-between border-b p-4"><div><div className="text-sm font-semibold">Purchase order · PO-2609-066</div><div className="text-[10px] text-muted-foreground">Submitted by Nadia Rahman · 18 minutes ago</div></div><div className="flex gap-2"><Button variant="outline" size="sm" className="rounded-sm shadow-none"><X/>Decline</Button><Button size="sm" className="rounded-sm shadow-none"><Check/>Approve</Button></div></div><OrderDetail purchase/></div></div></> }

export function AuditScreen(){return <><PageHeader eyebrow="Governance" title="Audit log" description="Filterable record of user activity and changes across every module." action="Export log"/><Panel title="System activity"><DataTable columns={[{key:"time",label:"Date & time"},{key:"user",label:"User"},{key:"action",label:"Action"},{key:"module",label:"Module"},{key:"record",label:"Record"},{key:"source",label:"Source"}]} rows={[{time:"12 Sep 2026 · 11:42",user:"Nadia Rahman",action:"Approved purchase order",module:"Purchase",record:"PO-2609-066",source:"Dhaka office"},{time:"12 Sep 2026 · 11:31",user:"Arif Hasan",action:"Updated sales price",module:"Products",record:"ZIP-NYL-09-BLK",source:"Dhaka office"},{time:"12 Sep 2026 · 10:58",user:"Maliha Islam",action:"Created payment",module:"Cash & Bank",record:"TXN-2609-181",source:"Gazipur"},{time:"12 Sep 2026 · 10:22",user:"System",action:"Low stock alert issued",module:"Inventory",record:"ELA-WOV-25",source:"Automated"}]}/></Panel></>}

export function VatTaxScreen(){const [tab,setTab]=useState("VAT report");return <><PageHeader eyebrow="Compliance" title="VAT & tax management" description="Configure applicable rates and review VAT collected and paid." action="Add tax rate"/><Panel title="Tax workspace"><TabsBar tabs={["VAT report","Tax rate configuration"]} active={tab} onChange={setTab}/>{tab==="VAT report"?<DataTable columns={[{key:"period",label:"Period"},{key:"sales",label:"Taxable sales",align:"right"},{key:"output",label:"Output VAT",align:"right"},{key:"purchase",label:"Taxable purchase",align:"right"},{key:"input",label:"Input VAT",align:"right"},{key:"net",label:"Net payable",align:"right"},{key:"status",label:"Status",status:true}]} rows={chartData.slice(3).map((r,i)=>({period:`${r.month} 2026`,sales:money(r.sales*100000),output:money(r.sales*5000),purchase:money(r.purchase*100000),input:money(r.purchase*5000),net:money((r.sales-r.purchase)*5000),status:i<4?"Completed":"Pending"}))}/>:<FormGrid title="Tax rate" fields={["Tax name","Rate (%)","Tax type","Effective from","Account code","Description"]}/>}</Panel></>}

const reportTabs=["Profit & Loss","Balance Sheet","Trial Balance","General Ledger","Aging Report"];
export function FinancialReportsScreen(){const [tab,setTab]=useState(reportTabs[0] ?? "Profit & Loss");const rows=tab==="Aging Report"?[{account:"Aurora Apparels",debit:money(482000),credit:"—",balance:money(482000),period:"0–30 days"},{account:"Northern Knitwear",debit:money(630000),credit:"—",balance:money(630000),period:"31–60 days"}]:[{account:"Sales revenue",debit:"—",credit:money(6248000),balance:money(6248000),period:"Sep 2026"},{account:"Cost of goods sold",debit:money(4126000),credit:"—",balance:money(4126000),period:"Sep 2026"},{account:"Operating expense",debit:money(588000),credit:"—",balance:money(588000),period:"Sep 2026"},{account:"Gross profit",debit:"—",credit:money(1534000),balance:money(1534000),period:"Sep 2026"}];return <><PageHeader eyebrow="Accounting" title="Financial reports" description="Standard financial statements and account-level analysis." action="Export report"/><Panel title="Financial statements"><TabsBar tabs={reportTabs} active={tab} onChange={setTab}/><div className="flex flex-wrap gap-2 border-b p-2"><Field label="From" type="date" defaultValue="2026-09-01"/><Field label="To" type="date" defaultValue="2026-09-30"/><Button size="sm" className="mt-[18px] h-8 rounded-sm">Run report</Button></div><DataTable searchable={false} columns={[{key:"account",label:"Account / Party"},{key:"period",label:"Period"},{key:"debit",label:"Debit",align:"right"},{key:"credit",label:"Credit",align:"right"},{key:"balance",label:"Balance",align:"right"}]} rows={rows}/></Panel></>}

export function WarehousesScreen(){const [tab,setTab]=useState("Warehouse stock");return <><PageHeader eyebrow="Locations" title="Multi-warehouse" description="Track storage locations, warehouse-level stock and internal transfers." action="Add warehouse"/><MetricStrip items={[{label:"Warehouses",value:"3",detail:"All locations active"},{label:"Tejgaon stock",value:money(3920000),detail:"624 SKUs"},{label:"Gazipur stock",value:money(2850000),detail:"418 SKUs"},{label:"In transfer",value:money(168000),detail:"4 open transfers"}]}/><Panel title="Warehouse operations"><TabsBar tabs={["Warehouse stock","Warehouse list","Stock transfer"]} active={tab} onChange={setTab}/>{tab==="Stock transfer"?<FormGrid title="Create stock transfer" fields={["Transfer number","From warehouse","To warehouse","Product / SKU","Quantity","Transfer date","Notes"]}/>:<DataTable columns={[{key:"sku",label:"SKU"},{key:"product",label:"Product"},{key:"warehouse",label:"Warehouse"},{key:"available",label:"Available",align:"right"},{key:"reserved",label:"Reserved",align:"right"},{key:"status",label:"Status",status:true}]} rows={inventoryRows}/>}</Panel></>}

export function AnalyticsScreen(){const reports=["Sales by buyer","Product profitability","Purchase by supplier","Inventory valuation","Receivable aging","Payable aging","VAT summary","Warehouse movement"];return <><PageHeader eyebrow="Reports" title="Reports & analytics center" description="Run operational and financial reports with consistent filters and exports." action="Saved reports"/><div className="mb-4 grid border-l border-t bg-card sm:grid-cols-2 lg:grid-cols-4">{reports.map((r,i)=><button type="button" key={r} className="group border-b border-r p-4 text-left hover:bg-muted"><FileText className="mb-5 size-5 text-primary"/><div className="text-xs font-semibold">{r}</div><div className="mt-1 text-[10px] text-muted-foreground">Updated {i<3?"today":"yesterday"}</div><ArrowRight className="ml-auto mt-3 size-3.5 text-muted-foreground group-hover:text-primary"/></button>)}</div><div className="grid gap-4 xl:grid-cols-[1fr_2fr]"><Panel title="Report filters"><div className="grid gap-3 p-4"><SelectField label="Report" options={reports}/><Field label="From date" type="date" defaultValue="2026-09-01"/><Field label="To date" type="date" defaultValue="2026-09-30"/><SelectField label="Warehouse" options={["All warehouses","Tejgaon","Gazipur","Narayanganj"]}/><Button size="sm" className="rounded-sm">Generate report</Button></div></Panel><Panel title="Sales by buyer" action={<Button variant="outline" size="sm" className="rounded-sm shadow-none"><Download/>Excel / PDF</Button>}><div className="h-72 p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Bar dataKey="sales" fill="var(--primary)" radius={0}/></BarChart></ResponsiveContainer></div></Panel></div></>}

export function SettingsScreen(){const [tab,setTab]=useState("Company profile");const tabs=["Company profile","Users & roles","Numbering","Tax & currency","Backup & export","Notifications"];return <><PageHeader eyebrow="Administration" title="Settings" description="Company identity, access control and system-wide defaults." action="Save changes"/><Panel title="System configuration"><TabsBar tabs={tabs} active={tab} onChange={setTab}/>{tab==="Users & roles"?<DataTable columns={[{key:"name",label:"User"},{key:"email",label:"Email"},{key:"role",label:"Role"},{key:"location",label:"Location"},{key:"status",label:"Status",status:true}]} rows={[{name:"Nadia Rahman",email:"nadia@garmenttrade.com",role:"Admin",location:"Dhaka",status:"Active"},{name:"Arif Hasan",email:"arif@garmenttrade.com",role:"Manager",location:"Gazipur",status:"Active"},{name:"Maliha Islam",email:"maliha@garmenttrade.com",role:"Staff",location:"Dhaka",status:"Active"}]}/>:tab==="Notifications"?<div className="divide-y">{[["Low stock alerts","Notify when stock falls below the product minimum"],["Approval reminders","Daily reminder for requests awaiting action"],["Payment due alerts","Notify seven days before buyer or supplier due date"],["Daily summary","Receive a closing summary of sales, purchase and cash"]].map((n,i)=><div key={n[0]} className="flex items-center justify-between p-4"><div><div className="text-xs font-semibold">{n[0]}</div><div className="text-[10px] text-muted-foreground">{n[1]}</div></div><Switch defaultChecked={i<3}/></div>)}</div>:<div className="p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label={tab==="Company profile"?"Company name":"Configuration name"} defaultValue={tab==="Company profile"?"GarmentTrade Accessories":"GT-Default"}/><Field label={tab==="Company profile"?"Phone":"Prefix"} defaultValue={tab==="Company profile"?"+880 2 5512 4400":"INV-{YYYY}-{####}"}/><Field label={tab==="Company profile"?"Email":"Default currency"} defaultValue={tab==="Company profile"?"accounts@garmenttrade.com":"BDT (৳)"}/><Field label="Address / Notes" defaultValue="Tejgaon Industrial Area, Dhaka 1208"/></div><div className="mt-4 border border-dashed p-5 text-center text-xs text-muted-foreground"><Building2 className="mx-auto mb-2 size-5"/>Company logo and invoice letterhead assets</div></div>}</Panel></>}
