/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as CashBankRouteImport } from './routes/cash-bank'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FinancialReportsRouteImport } from './routes/financial-reports'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as VatTaxRouteImport } from './routes/vat-tax'
import { Route as WarehousesRouteImport } from './routes/warehouses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBankRoute = CashBankRouteImport.update({
  id: '/cash-bank',
  path: '/cash-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialReportsRoute = FinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const VatTaxRoute = VatTaxRouteImport.update({
  id: '/vat-tax',
  path: '/vat-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/buyers': typeof BuyersRoute
  '/cash-bank': typeof CashBankRoute
  '/documents': typeof DocumentsRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/inventory': typeof InventoryRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/vat-tax': typeof VatTaxRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/buyers': typeof BuyersRoute
  '/cash-bank': typeof CashBankRoute
  '/documents': typeof DocumentsRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/inventory': typeof InventoryRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/vat-tax': typeof VatTaxRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/buyers': typeof BuyersRoute
  '/cash-bank': typeof CashBankRoute
  '/documents': typeof DocumentsRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/inventory': typeof InventoryRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/vat-tax': typeof VatTaxRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-log'
    | '/buyers'
    | '/cash-bank'
    | '/documents'
    | '/financial-reports'
    | '/inventory'
    | '/products'
    | '/purchase'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/vat-tax'
    | '/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-log'
    | '/buyers'
    | '/cash-bank'
    | '/documents'
    | '/financial-reports'
    | '/inventory'
    | '/products'
    | '/purchase'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/vat-tax'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-log'
    | '/buyers'
    | '/cash-bank'
    | '/documents'
    | '/financial-reports'
    | '/inventory'
    | '/products'
    | '/purchase'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/vat-tax'
    | '/warehouses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogRoute: typeof AuditLogRoute
  BuyersRoute: typeof BuyersRoute
  CashBankRoute: typeof CashBankRoute
  DocumentsRoute: typeof DocumentsRoute
  FinancialReportsRoute: typeof FinancialReportsRoute
  InventoryRoute: typeof InventoryRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseRoute: typeof PurchaseRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  VatTaxRoute: typeof VatTaxRoute
  WarehousesRoute: typeof WarehousesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-bank': {
      id: '/cash-bank'
      path: '/cash-bank'
      fullPath: '/cash-bank'
      preLoaderRoute: typeof CashBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-reports': {
      id: '/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof FinancialReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vat-tax': {
      id: '/vat-tax'
      path: '/vat-tax'
      fullPath: '/vat-tax'
      preLoaderRoute: typeof VatTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogRoute: AuditLogRoute,
  BuyersRoute: BuyersRoute,
  CashBankRoute: CashBankRoute,
  DocumentsRoute: DocumentsRoute,
  FinancialReportsRoute: FinancialReportsRoute,
  InventoryRoute: InventoryRoute,
  ProductsRoute: ProductsRoute,
  PurchaseRoute: PurchaseRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  VatTaxRoute: VatTaxRoute,
  WarehousesRoute: WarehousesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
